- name: Install unit file
  become: true
  copy: src=gog.service dest=/lib/systemd/system/ owner=root mode=644
  notify:
    - reload systemd
    - restart gog
- shell: systemctl enable gog
  become: true
